version: '3'

services:
  database:
    build: ./mysql-database
    restart: always
    container_name: mysql-database
    image: mysql-database
    ports:
    - "3306:3306"
    volumes:
      - storage:/var/lib/mysql
  app:
    build: ./rest-service
    image: rest-service
    container_name: rest-service
    links:
      - mysql-database
    ports:
    - "8080:8080"
    depends_on:
      - mysql-database
volumes:
  storage:
