version: '3'

services:
  mysql-database:
    build: ./mysql-database
    restart: always
    container_name: mysql-database
    image: mysql-database
    ports:
    - '3306:3306'
    volumes:
      - storage:/var/lib/mysql

  rest-service:
    build: ./rest-service
    container_name: rest-service
    image: rest-service
    ports:
    - '8080:8080'
    links:
      - mysql-database
    depends_on:
      - mysql-database

volumes:
  storage: